name: Update All Dependencies
on:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
      - name: Checkout Branch
        run: git checkout main
      - name: Configure CI Git User
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
      - name: Update
        run: |
          npm ci
          npm update
      - name: Git Push
        run: |
          git add package.json package-lock.json
          git commit -m "chore: update dependencies"
          git push
